name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Generate Lambda Packages
      run: |
        echo "wassah dude"
        ls -la
        
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      shell: bash
      run: |
        docker build -t 394414610569.dkr.ecr.us-east-1.amazonaws.com/clash_website_repo:latest .
        docker push 394414610569.dkr.ecr.us-east-1.amazonaws.com/clash_website_repo:latest

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Deploy Infra to AWS
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
      working-directory: infra

    


    